### ISSUE TITLE
Refactor code to improve reusability of the existing code

### ISSUE THREAD

**Issue by jshinm** [neurodata/treeple#17]
**Is your feature request related to a problem? Please describe.**
> With this particular task, make `sum_of_squares` global across classes. Maybe implement this in the parent class

**Describe the solution you'd like**
> Reuse `sum_of_squares` in different classes especially those that calculates variance

**Estimated completion date**
> Rough projected completion date is 2/17/2023. Originally planned to finish it after FastBIC implementation, but the task turned out to be straightforward, thus completed earlier

**Comment by jshinm** [comment]
@adam2392 just out of curiosity, why does sum_of_square require to be defined in pxd when things like `node_value` doesn't. Is this b/c those are already defined in the BaseCriterion?

**Comment by adam2392** [comment]
> @adam2392 just out of curiosity, why does sum_of_square require to be defined in pxd when things like `node_value` doesn't. Is this b/c those are already defined in the BaseCriterion?

Yep. It is analogous to header (.h) files in C++, and lets one cimport functions from. If it's not in header file then it's not discoverable. That's why I had to port the sklearn sort function. It's not in their header files.
