### ISSUE TITLE
Implement FastBIC criterion

### ISSUE THREAD

**Issue by jshinm** [neurodata/treeple#18]
**Is your feature request related to a problem? Please describe.**
> As a subtask of the initial unsupervised RF implementation effort, here we specifically detail timeframe of this task and discuss project

**Describe the solution you'd like**
> Finish implementing FastBIC as detailed in Meghana's 2019 paper

**Estimated completion date**
> Current timeline of the project is 1/30/2023 - 2/3/2023 (+2-3 days for documentation/rebranching/cleaning)

**Comment by jshinm** [comment]
Note: meson build doesn't actually install from source. It's only serving as a mechanism to see if cython builds correctly

**Comment by jshinm** [comment]
The `s` term is 0 at `note_impurity`! Thus 2 of the 4 terms from FastBIC final equation disappears which can be further simplified as $\text{N} * \log(2\sigma^2/\mu)$

**Comment by jshinm** [comment]
Noticed potential discrepancy from Meghana 2019 FastBIC equation. Discussed to use pseudocode implementation rather than the generalized form of the equation

**Comment by adam2392** [comment]
Closed by #45
