### ISSUE TITLE
Create unit test for FastBIC criterion

### ISSUE THREAD

**Issue by jshinm** [neurodata/treeple#19]
**Is your feature request related to a problem? Please describe.**
> Create appropriate unit test for FastBIC implementation.

**Describe the solution you'd like**
> This should run as part of meson test cycle

**Estimated completion date**
> Rough timeline for this task is 2/3/2023 - 2/8/2023. This task actually started on 2/5/2023 and expected time of completion is 1-3 days

**Comment by jshinm** [comment]
@adam2392 I've pushed Iris test in this [[PR](https://github.com/jshinm/scikit-tree/pull/3)], but it seems like it builds and tests fine, but it doesn't pass accuracy assertion. Did I misunderstand something here?

![Screenshot from 2023-02-07 00-33-10](https://user-images.githubusercontent.com/52612209/217157043-0173bfae-5289-464e-8ac8-710bb5e19bcc.png)

**Comment by adam2392** [comment]
The issue is that the axis-aligned trees are not as good as the oblique trees. The demo on the iris dataset by default in SPORF used the oblique trees. This requires my changes. You can set the relevant threshold to 0.6 for axis-aligned test instead of 0.9

**Comment by jshinm** [comment]
@adam2392 I ended up bringing it down to 0.3 b/c fastBIC scored 0.34, but with this, though, test_tree builds and tests

**Comment by adam2392** [comment]
Hmm okay... let's see what the forest test does. 

Could be an issue with implementation. But let's wait and see. 

Can we migrate convos regarding PRs into the PR itself?

**Comment by jshinm** [comment]
The changes have been applied and merged into #22
