### ISSUE TITLE
Another alternative way of estimating statistics for FeatureImportanceForestClassifier

### ISSUE THREAD

**Issue by sampan501** [neurodata/treeple#195]
From @jovo 

**Is your feature request related to a problem? Please describe.**
We sometimes get lower power with `FeatureImportanceForestClassifier` than previous methods, and one possible explanation is our 40-40-20 splits doesn't use very much data to learn tree structures or estimate posteriors well.

Related to #194 

**Describe the solution you'd like**
1. Bootstrap samples n times
2. In-bag to learn tree, OOB to estimate posteriors
3. Sample M times from the trees to estimate stats

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by adam2392** [comment]
See: https://github.com/neurodata/scikit-tree/issues/194#issuecomment-1961717393
