### ISSUE TITLE
Python 3.12 Support

### ISSUE THREAD

**Issue by sampan501** [neurodata/treeple#212]
## Checklist

- [ ] I have verified that the issue exists against the `main` branch.
- [ ] I have read the relevant section in the [contribution guide](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#bug-reports-and-feature-requests) on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/py-why/pywhy-graphs/issues) for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/py-why/pywhy-graphs/pulls) for existing proposed fixes.
- [ ] I have checked the [CHANGELOG](https://github.com/py-why/pywhy-graphs/blob/main/CHANGELOG.md) and the [commit log](https://github.com/py-why/pywhy-graphs/commits/main) to find out if the bug was already fixed in the main branch.
- [ ] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [ ] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [ ] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

Wheels are not built for any operating systems for Python 3.12

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Collecting scikit-tree
  Using cached scikit_tree-0.6.0.tar.gz (16.3 MB)
ERROR: scikit-tree from https://files.pythonhosted.org/packages/91/77/d5d6e3c5289c36cb76679c8de12f584721df30e741c318a4213f49bbfaf9/scikit_tree-0.6.0.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS:

Python version:

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by adam2392** [comment]
Also fixed in latest commit to `main`
