### ISSUE TITLE
Questions about modifiable local installation of scikit learn

### ISSUE THREAD

**Issue by awyuan** [neurodata/treeple#233]
Hello,

I am trying to install a modifiable scikit-tree version locally to add some parameters to decision trees for a research project I am working on and I was having issues with locally install scikit-tree and being able to modify it and have it reflect in other code that calls on the functions. I'm unfamiliar with the process modifying python packages, so apologies if some of the questions are basic. 

The first problem I am getting is trying to call any scikit-tree classes like _splitter or _criterion. When I run through the instructions given in the guideline, everything runs fine, and I can see that I've installed the right version of scikit-tree. However, whenever I go to try to ``` from sktree.tree import _splitter```, it is unable to find it (I've also tried ```sktree.tree._lib.sklearn.tree.splitter```, but that also isn't found). 

The second problem is actually maintaining the changes I make to the C files. Which command should I be running to compile the C code? It seems like whenever I run ```spin build```, whatever changes I make locally are being overwritten. 

Thanks for the help.

**Comment by adam2392** [comment]
The development guide discusses how to install: https://github.com/neurodata/scikit-tree/blob/main/DEVELOPING.md. If there is any confusion, feel free to post some details.

As for your other questions regarding importing _splitter and _criterion, I don't think that is [supported](https://docs.neurodata.io/scikit-tree/dev/api.html), so unsure what you're trying to do. Can you elaborate?

**Comment by awyuan** [comment]
Hi Adam, thanks for responding. I essentially want to add hyperparameters to DecisionTrees to support an application I am building. Some of the hyperparams would occur in the splitter_ file and basically add additional conditions to the splitting process. I found this repo because it better abstracts these classes than scikit-learn does natively, but I'm having trouble getting these 3 steps to work:
1. Install scikit-learn fork locally
2. Add hyperparameters to the decision tree classifier and the splitter
3. Be able to see the changes in a downstream classification task when importing the new classifier.

I've followed the steps in both the readme and developing files, but while I can import sktree.tree, I can't import any files below that level without running into errors. I was hoping to get a better sense on if I've done something fundamentally wrong while trying to get the tasks above to work.

**Comment by adam2392** [comment]
In order to modify the splitter, you need to use Cython. You should be able to import everything, and I can't replicate any error that you're describing unfortunately.

**Comment by awyuan** [comment]
The issue has been solved, we were trying to import from within parent library causes issues. Installing it to a separate folder solved the issues we were having.

**Comment by adam2392** [comment]
Closing this issue, but feel free to reopen if there are any issues.
