### ISSUE TITLE
ENH treeple tutorials should use native functions in scikit-tree

### ISSUE THREAD

**Issue by sampan501** [neurodata/treeple#257]
From #256:

We should fix the tutorials to use native functions in scikit-tree, like `build_coleman_forest` etc. It should be clear to the user that they don't need to write their own custom function to compute a p-value using MIGHT.

**Comment by PSSF23** [comment]
Jovo wants to add a figure similar to[ this one](https://www.researchgate.net/figure/The-null-distribution-of-the-test-statistic-in-4-for-the-null-hypothesis-that-there-is_fig1_304858060), which would require all the intermediate statistics (the ones that 2 permuted forest make). `build_coleman_forest` doesn't return those values, unfortunately, so I'll postpone the conversion for now.

**Comment by sampan501** [comment]
Sure, we could write it like this instead. Show all the intermediate stats figures, and at the end show how to compute the stat and p-value using treeple

**Comment by adam2392** [comment]
The statistics we need are the null distribution? What else?

**Comment by adam2392** [comment]
I assume this has been addressed in #280 and #273. Feel free to reopen if not.
