### ISSUE TITLE
[Easy, Python] Add Regressor tree and forest classes for Oblique and Patch trees

### ISSUE THREAD

**Issue by adam2392** [neurodata/treeple#28]
Add the regressor version of each type of tree.

**Comment by adam2392** [comment]
One would review the differences of DecisionTreeClassifier vs DecisionTreeRegressor and RandomForestClassifier vs RandomForestRegressor (note that it's pretty much a few kwarg changes) and then look at how we can implement an analogous set of regressor classes for the Oblique and PatchOblique tree.

**Comment by adam2392** [comment]
Xref:

- (olique trees) https://jmlr.org/papers/v21/18-664.html
- (patch oblique trees - called MORF in this paper) https://epubs.siam.org/doi/abs/10.1137/21M1449117

cc: @SUKI-O

**Comment by jdey4** [comment]
@adam2392 is this issue resolved or do you need help with this? I can help with some of the issues.

**Comment by adam2392** [comment]
@jdey4 this was addressed by https://github.com/neurodata/scikit-tree/pull/72. 

Sorry forgot to close this!
