### ISSUE TITLE
Treeple pypi page not accessible

### ISSUE THREAD

**Issue by ritviksahajpal** [neurodata/treeple#296]
https://pypi.org/project/treeple/ is not accessible. I get an error message saying "We looked everywhere but couldn't find this page"

When I try to do `pip install treeple` I get the error:
ERROR: Could not find a version that satisfies the requirement treeple (from versions: none)
ERROR: No matching distribution found for treeple

thanks for developing this package.

**Comment by adam2392** [comment]
Hi @ritviksahajpal it should be up now on PyPi v0.9.1. Apologies as we transitioned the package to a new name.

The documentation page should shortly be updated as well.

cc: @SUKI-O

**Comment by adam2392** [comment]
Hi @ritviksahajpal v0.9.1. is released. I'll close the issue now, but feel free to reopen if you have issues.
