### ISSUE TITLE
Bottleneck should not raise a warning unless relevant function in treeple.stats is called

### ISSUE THREAD

**Issue by adam2392** [neurodata/treeple#310]
These lines seem like they are ran regardless of whether or not treeple.stats is used, since they are in the global namespace.

```
if BOTTLENECK_AVAILABLE and DISABLE_BN_ENV_VAR not in os.environ:
    nanmean_f = bn.nanmean
    anynan_f = lambda arr: bn.anynan(arr, axis=2)
else:
    warnings.warn(
        "Not using bottleneck for calculations involvings nans. Expect slower performance."
    )
    nanmean_f = np.nanmean
    anynan_f = lambda arr: np.isnan(arr).any(axis=2)
```

so I get this warning consistently no matter what

```
/Users/adam2392/Documents/treeple/treeple/stats/utils.py:34: UserWarning: Not using bottleneck for calculations involvings nans. Expect slower performance.
  warnings.warn(
```

@ryanhausen do you mind submitting a PR to patch this behavior?

**Comment by ryanhausen** [comment]
@adam2392 sure! This warning should have only shown when treeple.stats is imported? Were you seeing it at other times?

**Comment by adam2392** [comment]
Yeah I think because we do imports in `__init__.py`

<img width="636" alt="Screenshot 2024-08-08 at 9 43 00 AM" src="https://github.com/user-attachments/assets/2ac09f9d-5bef-401d-86ac-b668e59ea759">

I would take a look at the strategy, or designs sklearn uses to soft-import optional dependencies. E.g. polars, or joblib

**Comment by adam2392** [comment]
Just to clarify @ryanhausen rather than warning during import, it should only warn the user when the function is used

**Comment by ryanhausen** [comment]
@adam2392 agreed.
