### ISSUE TITLE
Getting `TypeError check_array() got an unexpected keyword argument 'ensure_all_finite'` causing many tests to fail

### ISSUE THREAD

**Issue by ryanhausen** [neurodata/treeple#314]
## Checklist

- [x] I have verified that the issue exists against the `main` branch.
- [x] I have read the relevant section in the [contribution guide](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#bug-reports-and-feature-requests) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/py-why/pywhy-graphs/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/py-why/pywhy-graphs/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/py-why/pywhy-graphs/blob/main/CHANGELOG.md) and the [commit log](https://github.com/py-why/pywhy-graphs/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section below all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

It looks like something has changed is the check_array() API in the underlying sklearn fork and now the marjority of tests fail for me. I might be installing it incorrectly, but I am not sure where the mistake is.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
treeple/tree/_classes.py:231: in fit
    sim_mat = self.compute_similarity_matrix(X)
treeple/tree/_neighbors.py:66: in compute_similarity_matrix
    return compute_forest_similarity_matrix(self, X)
treeple/tree/_neighbors.py:30: in compute_forest_similarity_matrix
    X_leaves = forest.apply(X)[:, np.newaxis]
treeple/_lib/sklearn/tree/_classes.py:868: in apply
    X = self._validate_X_predict(X, check_input)
treeple/_lib/sklearn/tree/_classes.py:645: in _validate_X_predict
    X = self._validate_data(
TypeError: check_array() got an unexpected keyword argument 'ensure_all_finite'
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Linux

Python version: 3.9.19

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
Bottleneck==1.4.0
build==1.2.1
click==8.1.7
cloudpickle==3.0.0
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
coverage==7.6.1
Cython==3.0.11
doit==0.36.0
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1720869315914/work
flaky==3.8.1
importlib_metadata==8.2.0
iniconfig @ file:///home/conda/feedstock_root/build_artifacts/iniconfig_1673103042956/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1714665484399/work
markdown-it-py==3.0.0
mdurl==0.1.2
memory-profiler==0.61.0
meson==1.5.1
meson-python==0.16.0
ninja==1.11.1.1
numpy==2.0.1
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1718189413536/work
pandas==2.2.2
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1713667077545/work
psutil==6.0.0
pydevtool==0.3.0
Pygments==2.18.0
pyproject-metadata==0.8.0
pyproject_hooks==1.1.0
pytest @ file:///home/conda/feedstock_root/build_artifacts/pytest_1721923606331/work
pytest-cov==5.0.0
python-dateutil==2.9.0.post0
pytz==2024.1
rich==13.7.1
rich-click==1.8.3
scikit-learn==1.5.1
scipy==1.13.1
six==1.16.0
spin==0.11
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1714400101435/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
tqdm==4.66.5
typing_extensions==4.12.2
tzdata==2024.1
zipp==3.20.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
git clone git@github.com:neurodata/treeple.git
cd treeple
conda create -n treeple python=3.9
conda activate treeple
python -m pip install -r build_requirements.txt
conda install -c conda-forge joblib threadpoolctl pytest compilers llvm-openmp
./spin build 
python -m pip install -r test_requirements.txt 
./spin test
```

</p>
</details>

**Comment by adam2392** [comment]
This is due to `main` treeple not being compatible with `scikit-learn` pip released version. But when they release another version, we can do a release as well.

**Comment by ryanhausen** [comment]
That makes sense, would it make sense to change the developer/contributor docs to install the scikit learn from the main then?

I am happy to submit a PR you're interested. I think at a high-level, we would drop scikit-learn from the `build_requirements.txt` and either add another requirements file or a manual pip install with the following:

```
pip install --pre --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple scikit-learn
```

Does that seem right?

**Comment by ryanhausen** [comment]
That makes sense, would it make sense to change the developer/contributor docs to  install the scikit learn from the main then?

I am happy to submit a PR you're interested. I think at a high-level, we would drop scikit-learn from the `build_requirements.txt` and either add another requirements file or a manual pip install with the following:

```
pip install --pre --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple scikit-learn
```

Does that seem right?

**Comment by adam2392** [comment]
I would only change the developer documentation

A PR would be great.
