### ISSUE TITLE
[ENH] Add honest trees

### ISSUE THREAD

**Issue by sampan501** [neurodata/treeple#56]
**Is your feature request related to a problem? Please describe.**
Want to extend current implementations of SPORF and decision trees in scikit-learn to be honest.

**Describe the solution you'd like**
Port code from [neurodata/honest-forests](https://github.com/neurodata/honest-forests) into this repo into scikit-tree. Based on issue #29 except specific for the honesty portion.

**Describe alternatives you've considered**
Code written by @rflperry in the [neurodata/honest-forests](https://github.com/neurodata/honest-forests) repo.

**Additional context**
See issue #29

**Comment by adam2392** [comment]
@sampan501 another thing to keep in mind is when we use existing criterion, such as Gini criterion, this tries to split the tree until the leaves are "pure", which is not what we want. I.e. the leaves should contain `k` samples from each treatment group (assuming T is discrete). 

Thoughts are perhaps, this can be controlled using existing decision tree hyperparameters such as `min_samples_leaf` and `min_weight_leaf`, but this brings up complications when `sample_weight` is defined, or T multiple groups i.e. {0, 1, 2, ...}.

Alternatively, I have added a way for us to generalize the pre split and post-split stopping conditions, which we can add some logic for making sure the children are "heterogenous" enough. https://github.com/neurodata/scikit-learn/blob/2a24ea6b5192e423c21f7e8565611c3579b5a9f6/sklearn/tree/_splitter.pyx#L276-L309

Just food for thought. Probably to be addressed in the next PR

<img width="808" alt="Screenshot 2023-03-23 at 11 30 24 AM" src="https://user-images.githubusercontent.com/3460267/227253634-7f29b230-d8c2-48ab-bf1e-fdec04f2f6fb.png">

**Comment by adam2392** [comment]
@PSSF23 thanks for adding honesty! now propensity trees should enable us to do causal tree stuff!
