### ISSUE TITLE
Implementation of Two-Means and Fast-BIC criterion and unsupervised decision trees

### ISSUE THREAD

**Issue by adam2392** [neurodata/treeple#6]
**Is your feature request related to a problem? Please describe.**
Once `Criterion` and `Splitter` are properly modularized inside scikit-learn, a first step for us to take advantage of this modularity would be to implement the unsupervised decision tree. This will build a tree using only `X`, rather than `y`. 

I have implemented the skeleton/boilerplate for the Two-Means and the base class of `UnsupervisedCriterion`. Scikit-learn supports splitting on both sparse and dense data. For our purposes, we will focus on supporting only dense data for now.

**Describe the solution you'd like**

The full solution should be Cython and Python code to implement the unsupervised decision tree using either `TwoMeans` criteria or `FastBIC` criteria. The tasks that need to be implemented are:

#### In Cython

1. [x] Finish implementation of the functions inside `TwoMeans` class inside `_unsup_criterion.pyx`. The main challenges are probably implementing `node_value`. 
2. [x] Implement `UnsupervisedSplitter` inside a new `_unsup_splitter.pyx` and pxd file for the abstract base class for unsupervised splitters.
3. [x] Implement a `BestDenseSplitter` just copying more or less the code from scikit-learn. Note the functionality in scikit-learn doesn't even rely on `y`.
4. [x] Implement an `UnsupervisedTree` class more or less copying a lot of code from scikit-learn
5. [x] Implement an `UnsupervisedTreeBuilder` class and `UnsupervisedBestFirstTreeBuilder` class also more or less copying a lot of code from scikit-learn

#### In Python
1. [x] Implement a `UnsupervisedBaseDecisionTree` class, similar to `BaseDecisionTree`. If we have the issue/PR merged in by then modularizing the Tree class for unsupervised settings, then we can probably inherit from `BaseDecisionTree`. If not, copy for now.
2. [x] Implement a `UnsupervisedRandomForest` class, similar to the `RandomForestClassifier`.
3. [x] Implement unit test cases based on the paper
4. [ ] Re-implement an example doc like https://sporf.neurodata.io/demos/urerf/iris_unsupervised_classification
5. [ ] Additional experiments to make us believe the implementation is correct...

At the end of this PR, there should be the additional Cython files inside `tree/`: `_unsup_splitter.pyx`, `_unsup_splitter.pxd`, `_unsup_tree.pxd`, `_unsup_tree.pyx` and `_unsup_classes.py`.

Note that this package hasn't setup a solid CI/dev build process, so those may be added along the way to make the dev process simpler.

**Additional context**
See: https://arxiv.org/pdf/1907.02844.pdf

@jshinm and @jovo this I think is a good first project for Jong. The Oblique PR will have to wait for a few modularity improvements (I really don't want to copy/paste large tree files unless necessary).

Why are unsupervised decision trees interesting to me? We can use them to estimate conditional mutual information. Rn it has been shown to estimate MI. https://arxiv.org/abs/2110.13883. We want better CMI estimates because they are central for causal discovery algorithms. Note that CMI estimation is a novel idea and would result in a paper once we implement the above.

**Comment by jovo** [comment]
@adam2392 That's great, we care deeply about CMI.  Of note, in this paper, we use RF to consistently estimate MI: https://arxiv.org/abs/1907.00325.  Estimating CMI from it is relatively straightforward, and we are working on that now.  As you can see from that paper, we don't need unsupervised to estimate MI or CMI, we can use supervised.  So, I don't see why you want unsupervised to estimate CMI.  I want unsupervised to do manifold learning and structure learning in high dimensions.  Sambit and Yuxin are working on a related paper now.

**Comment by adam2392** [comment]
@jovo In https://arxiv.org/abs/1907.00325, estimating MI/CMI only works on discrete data in the supervised setting IIUC. 

We can go a step further by using unsupervised decision trees to estimate adaptive nearest-neighbors as a plug-in for the [KNN-approach estimate of CMI](https://www.researchgate.net/profile/Stefan-Frenzel-2/publication/5619101_Partial_Mutual_Information_for_Coupling_Analysis_of_Multivariate_Time_Series/links/581329e308aedc7d8960c356/Partial-Mutual-Information-for-Coupling-Analysis-of-Multivariate-Time-Series.pdf). 

Based on what I discussed w/ Sambit:
- supervised is great as well cuz we want estimators of CMI in discrete settings
- unsupervised is great because we can do a two-stage estimation of CMI: i) estimate nearest neighbors (in manifolds optionally), and ii) plug in kNN estimates into the kNN-estimate-of-CMI

^ Perhaps we should have both in a single unified paper? I.e. "A more general approach to estimating high-dimensional CMI with decision trees"

**Comment by adam2392** [comment]
> - [ ] Re-implement an example doc like https://sporf.neurodata.io/demos/urerf/iris_unsupervised_classification
> - [ ] Additional experiments to make us believe the implementation is correct...

These two issues are left along with the implementation of `FastBIC` criterion

**Comment by adam2392** [comment]
Closed by #45
